# Generated by Django 5.0 on 2024-01-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_foodcomment_commenter'),
        ('stores', '0003_alter_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='stores.store'),
        ),
    ]
