# Generated by Django 5.0 on 2023-12-18 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tastytakout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyerLikeFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerLikeStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "sender",
                    models.CharField(
                        choices=[("STORE", "Store"), ("BUYER", "Buyer")], max_length=5
                    ),
                ),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_urls", models.JSONField()),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("rating", models.FloatField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tastytakout.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tastytakout.food",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_amount", models.IntegerField()),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("PERCENT", "Percent")], max_length=8
                    ),
                ),
                ("end", models.DateTimeField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tastytakout.food",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                        ],
                        max_length=8,
                    ),
                ),
                ("total", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("BANKING", "Banking")], max_length=8
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("total", models.IntegerField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tastytakout.food",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tastytakout.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("image_url", models.TextField()),
                ("address", models.TextField()),
                ("email", models.TextField()),
                ("license_image_url", models.TextField()),
                ("owner_name", models.TextField()),
                ("note", models.TextField()),
                ("deny_reason", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                        ],
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("password", models.TextField()),
                ("auth_id", models.IntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("BUYER", "Buyer"), ("SELLER", "Seller")],
                        max_length=10,
                    ),
                ),
                ("PIN", models.TextField()),
                ("avatar_url", models.TextField()),
                ("name", models.TextField()),
                ("bio", models.TextField()),
                ("phone", models.TextField()),
                ("address", models.TextField()),
                ("date_of_birth", models.DateTimeField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(unique=True)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("used_quantity", models.IntegerField()),
                ("end", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("discount_amount", models.IntegerField()),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("PERCENT", "Percent")], max_length=8
                    ),
                ),
                ("max_price", models.IntegerField()),
                ("min_price", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="cart",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.food"
            ),
        ),
        migrations.AddField(
            model_name="buyerlikefood",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.food"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.store"
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.store"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.store"
            ),
        ),
        migrations.AddField(
            model_name="buyerlikestore",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.store"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.user"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.user"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.user"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.user"
            ),
        ),
        migrations.AddField(
            model_name="buyerlikestore",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.user"
            ),
        ),
        migrations.AddField(
            model_name="buyerlikefood",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tastytakout.user"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="voucher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tastytakout.voucher",
            ),
        ),
    ]
