# Generated by Django 5.0 on 2023-12-24 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], max_length=8)),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANKING', 'Banking')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('used_quantity', models.IntegerField()),
                ('end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount_amount', models.IntegerField()),
                ('discount_type', models.CharField(choices=[('CASH', 'Cash'), ('PERCENT', 'Percent')], max_length=8)),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
            ],
        ),
    ]
