# Generated by Django 5.0 on 2024-01-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_store_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARE', 'Prepare'), ('DELIVERING', 'Delivering'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
    ]
